### ISSUE TITLE
Implement Devanagari number formatting

### ISSUE THREAD

**Issue by sndsabin** [techgaun/get-nepali-number#1]
Currently, the behaviour is:
```
getNepaliNumber('100')           => '१००'
getNepaliNumber('1000')          => '१०००'
getNepaliNumber('1,000,365.50')  => '१,०००,३६५.५०'
```

**Proposal**

 Implement Devanagari number formatting : 
```
getNepaliNumber('100')           => '१००'
getNepaliNumber('1000')          => '१,०००'
getNepaliNumber('1,000,365.50')  => '१०,००,३६५.५'
```

**Comment by techgaun** [comment]
@sndsabin great idea. I'm currently not able to support this for next couple of weeks but I'll keep this in my mind after that. If you (or anyone using this) wants to work on this, feel free to raise a PR.
